### ISSUE TITLE
Adding RDS objects to repository

### ISSUE THREAD

**Issue by julianSchwab** [ms-balzer/IRI_adaptive_maladaptive_kidney_regeneration#1]
Congrats to this great work!

I am trying to have a look on your data, however, sadly, it seems I am working on it the wrong way. Could you maybe add the RDS-files used in your code, for easier reproducability? And is the code, which produces Figure 1g of the paper also in this repo? I would really be interested in how to produce such a graph :)

**Comment by ms-balzer** [comment]
Hi Julian,

We have shared processed data including the RDS object on GEO that you can use: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?&acc=GSE180420

Figure 1g is a simple UMAP graph that was created with Seurat, you find the functions how to create a UMAP plot here: https://satijalab.org/seurat/articles/pbmc3k_tutorial.html.

Hope this helps. Best, Michael

**Comment by ms-balzer** [comment]
See above

**Comment by julianSchwab** [comment]
Thank you very much, Michael!
I started using the "GSE180420_EXPORT_counts.rds.gz" file from NCBI GEO, processed the counts according to the LIGER.R script of this repo. Next, I used the created Seurat-object for UMAP plotting, however the plot looks very much different to the figure of your paper. So, it seems I am doing something wrong or miss any preprocessing steps (sample and gene numbers are matching to you comments in the code) and this is why I was asking for the specific code to plot this figure with the according preprocessing. 
About the RDS-files, for the monocle scripts you load RDS-files, such as "PT1.7kbarcodes.rds", which I do not understand how to reproduce.
Thanks again in advance.

Best, Julian

**Comment by ms-balzer** [comment]
Please use the UMAP embeddings shared on GEO. This corresponds to the output of the LIGER-Seurat pipeline as described in the paper. The LIGER pipeline is for when you want to start from 10x output, not from the processed RDS.

**Comment by julianSchwab** [comment]
ok, thanks. But I want to work on the data with similar processing. According to the paper, the raw data is in GEO, so I need to run LIGER etc., or am I wrong? So my question is, which steps I have to run to come from the data in GEO to the UMAP embeddings in GEO? This is where I seem to do something wrong, trying to use the code of this repo.

Bests, Julian

**Comment by julianSchwab** [comment]
?
